weights: models/Cable1/A/yolo/weights/best.pt
device: cpu
conf_thres: 0.4
iou_thres: 0.45
imgsz:
- 640
- 640
timeout: 1
enable_yolo: true
output_dir: Result
current_product: Cable1
current_area: A
expected_items:
  Cable1:
    A:
    - Red
    - Green
    - Orange
    - Yellow
    - Black
    - Black
pipeline:
- color_check
- count_check
- sequence_check
- save_results
steps:
  count_check:
    strict: true
  sequence_check:
    direction: left_to_right
    expected:
    - Red
    - Green
    - Orange
    - Yellow
    - Black
    - Black
enable_color_check: true
color_checker_type: stats
color_model_path: models/Cable1/A/yolo/color_stats.json
