weights: weights/best.pt
device: cpu
conf_thres: 0.2
iou_thres: 0.45
imgsz:
- 640
- 640
timeout: 1
enable_yolo: true
output_dir: Result
current_product: Cable1
current_area: A
expected_items:
  Cable1:
    A:
    - Red
    - Green
    - Orange
    - Yellow
    - Black
    - Black
pipeline:
- color_check
- count_check
- sequence_check
- save_results
steps:
  count_check:
    strict: true
  sequence_check:
    direction: left_to_right
    expected:
    - Red
    - Green
    - Orange
    - Yellow
    - Black
    - Black
enable_color_check: true
color_checker_type: stats
color_model_path: color_stats.json
position_config:
  Cable1:
    A:
      enabled: true
      mode: bbox
      tolerance: 0.0
      expected_boxes:
        Red:
          x1: 97
          y1: 315
          x2: 334
          y2: 431
        Orange:
          x1: 155
          y1: 321
          x2: 391
          y2: 437
        Black:
          x1: 210
          y1: 318
          x2: 477
          y2: 452
        Yellow:
          x1: 183
          y1: 320
          x2: 418
          y2: 441
        Green:
          x1: 125
          y1: 318
          x2: 364
          y2: 432
      imgsz: 640
      tolerance_unit: percent
