weights: "D:/Git/robotlearning/yolo11_inference/models/LED/B/yolo/LED_color_mixing_best.pt"
device: "cpu"
conf_thres: 0.3
iou_thres: 0.45
imgsz: [640, 640]
timeout: 1
current_product: "LED"
enable_yolo: true
enable_color_check: true           # 是否啟用顏色檢查
color_model_path: "models/LED/B/yolo/enhanced_model.json"
color_threshold_overrides:
  Red: 1
output_dir: Result

# Saving controls (tune IO and file size)
save_fail_only: true         # only save images for FAIL results
save_original: true          # save original frame
save_processed: false        # skip processed image to reduce IO
save_annotated: true         # keep annotated for review
save_crops: false            # skip per-detection crops for performance
jpeg_quality: 90             # 1-100, higher = better quality/larger file
png_compression: 3           # 0-9, higher = smaller/slower
max_crops_per_frame: 0       # 0 or null means unlimited (ignored if save_crops=false)

expected_items:
  LED:

    B:
      - Red
      - Red
      - Red
      - Red
      - Red
      - Red
      - Red
      - Red
      - Red



position_config:
  PCBA1:
    A:
      enabled: false
      mode: bbox
      tolerance: 2
      expected_boxes:
        C22B: { x1: 350, y1: 210, x2: 390, y2: 310 }
        J5-1: { x1: 400, y1: 200, x2: 540, y2: 340 }
        J5-2: { x1: 80,  y1: 250, x2: 180, y2: 380 }
        J6:   { x1: 200, y1: 250, x2: 320, y2: 380 }
        J7:   { x1: 430, y1: 270, x2: 580, y2: 400 }
